name: avacado_blog_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.8
  flutter_screenutil: ^5.9.0
  dio: ^5.3.3
  provider: ^6.0.5
  # youtube_player_flutter: ^8.0.0
  webview_flutter: ^2.0.13 
  shimmer: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - asset/icons/
    - asset/images/
    - asset/logos/



 